FROM brunokarpo/openjdk-8
LABEL maintainer="Bruno Nogueira <ti.brunonogueira at gmail.com>"
RUN mkdir -p /app/
ADD build/libs/*.jar /app/lab-4-word.jar
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=subject", "/app/lab-4-word.jar"]
#
#FROM brunokarpo/openjdk-8
#LABEL maintainer="Bruno Nogueira <ti.brunonogueira at gmail.com>"
#RUN mkdir -p /app/
#ADD build/libs/*.jar /app/lab-4-word.jar
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=verb", "/app/lab-4-word.jar"]
#
#FROM brunokarpo/openjdk-8
#LABEL maintainer="Bruno Nogueira <ti.brunonogueira at gmail.com>"
#RUN mkdir -p /app/
#ADD build/libs/*.jar /app/lab-4-word.jar
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=adjective", "/app/lab-4-word.jar"]
#
#FROM brunokarpo/openjdk-8
#LABEL maintainer="Bruno Nogueira <ti.brunonogueira at gmail.com>"
#RUN mkdir -p /app/
#ADD build/libs/*.jar /app/lab-4-word.jar
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=article", "/app/lab-4-word.jar"]
#
#FROM brunokarpo/openjdk-8
#LABEL maintainer="Bruno Nogueira <ti.brunonogueira at gmail.com>"
#RUN mkdir -p /app/
#ADD build/libs/*.jar /app/lab-4-word.jar
#ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=noun", "/app/lab-4-word.jar"]